### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by agamjotsingh18** [agamjotsingh18/pollitup#1]

**Comment by Sanket1308** [comment]
I want to work on this issue under JWOC. Please assign me this issue. I would like to contribute to it.

**Comment by agamjotsingh18** [comment]
Sure @Sanket1308

**Comment by Sanket1308** [comment]
I have made a PR. Kindly check.

**Comment by KendallDoesCoding** [comment]
Believe this issue has been fixed, please close this issue @agamjotsingh18
