### ISSUE TITLE
Correcting the 'Share Profile' copy link

### ISSUE THREAD

**Issue by Bhavil-Ahuja** [agamjotsingh18/pollitup#109]
## Expected Behavior

When you click on 'Share' button in your profile, it should take you to the right URL for displaying the profile page (which is specified in the route paths in the 'App.js' file). So we append the custom URL part after the window.location.href path.

## Current Behavior

When you click on 'Share' button in your profile, it copies the wrong URL which won't display any page. It opens up the page with the domain 'pollitup.ink'. However, according to the routing paths in the 'App.js' file, it should open the URL corresponding to the current URL, which according to the current published website should be 'pollitup.netlify.app'.

**Comment by agamjotsingh18** [comment]
Sure @Bhavil-Ahuja
