### ISSUE TITLE
Shifting dark mode button to top

### ISSUE THREAD

**Issue by agamjotsingh18** [agamjotsingh18/pollitup#11]
shifting the dark mode button to top without compromising with the design of the website

**Comment by coder-mohit** [comment]
hey can you assign these issue to me

**Comment by Rohan-Hazari** [comment]
I would like to work on this issue under JWOC

**Comment by agamjotsingh18** [comment]
@coder-mohit sure

**Comment by Shruti025** [comment]
hey, can I work on this issue under JWOC?

**Comment by ronitblenz** [comment]
He hasnt turned up, could you assign me for this issue?

**Comment by coder-mohit** [comment]
> He hasnt turned up, could you assign me for this issue?

Check closed pr
