### ISSUE TITLE
Connect Create Pole form to Firebase Backend

### ISSUE THREAD

**Issue by aceta-minophen** [agamjotsingh18/pollitup#112]
## Expected Behavior

The data entered by users in poles should be sent to Firestore with all the necessary parameters against the username. 

## Current Behavior
When we are creating a form now the data isn't being posted on Firestore, and hence cannot be retrieve it to display the poll on the Dashboard.

**Comment by debsouryadatta** [comment]
I want to work on this issue, can you please assign it to me.

**Comment by agamjotsingh18** [comment]
Sure @debsouryadatta
