### ISSUE TITLE
Read from Firestore to display polls on Dashboard

### ISSUE THREAD

**Issue by aceta-minophen** [agamjotsingh18/pollitup#113]
## Expected Behavior

The website should display poll information by fetching data from Firestore.

## Current Behavior

The current code is not connected to Firestore backend hence the polls aren't shown on the Dashboard.

**Comment by MahendraDani** [comment]
@aceta-minophen I would like to work on this!

**Comment by aceta-minophen** [comment]
@MahendraDani sure, go ahead.

**Comment by MahendraDani** [comment]
@aceta-minophen 
I am sorry mam, I am incapable for solving this issue.
Please assign it other contributors.
I will try to work on some other issues.

I am extremely sorry!
Thanks for cooperation and support.

**Comment by Arnabdaz** [comment]
completed by #144
