### ISSUE TITLE
Implement the password reset functionality form firebase

### ISSUE THREAD

**Issue by Arnabdaz** [agamjotsingh18/pollitup#122]
### Current behavior:
the password reset pages are already implemented but the password reset functionality doesn't work

### Expected behavior:
The password reset functionality should send reset password mail on doing the password reset.

**Comment by AmoghCreator** [comment]
@aceta-minophen Please assign this issue to me :-)

**Comment by aceta-minophen** [comment]
@AmoghCreator the issue has been assigned to you go ahead

**Comment by Arnabdaz** [comment]
@AmoghCreator are you still working on it ?

**Comment by AmoghCreator** [comment]
@Arnabdaz yes, I am sorry for the delay, my laptop is in for repair, I will try to complete it as soon as I get it back.

**Comment by Deepanshu0703** [comment]
Hey @Arnabdaz can you assign me this issue. As this issue is inactive for a month.

**Comment by Arnabdaz** [comment]
@Deepanshu0703 go ahead

**Comment by Deepanshu0703** [comment]
hey @Arnabdaz getting this error after cloning and following the steps mentioned in the readme 

![image](https://github.com/agamjotsingh18/pollitup/assets/114489502/2a096814-b859-43aa-9ed7-6b1e1e4a2eae)

Can you pls brief me about how to setup this
