### ISSUE TITLE
Add Feature Request 

### ISSUE THREAD

**Issue by andoriyaprashant** [agamjotsingh18/pollitup#141]
# Description

I plan to create Feature Request Forms.

The Feature Request issue form will have the following fields

- Is your feature request related to a problem? Please describe.
- Describe the solution you'd like
- Describe alternatives you've considered

## Prerequisites

-  I am running the latest version
-  I checked the documentation and found no answer
-  I checked to make sure that this issue has not already been filed
-  I'm reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

feature_request.yml file in .github folder

## Current Behavior

There is not feature request template

**Comment by andoriyaprashant** [comment]
Hello @agamjotsingh18 
Please assign me this issue 
Thank you

**Comment by Arnabdaz** [comment]
hey @andoriyaprashant sorry i merged the issue without adding gssoc tag ... but i also want you to update the current issue template and make it a bit easier and add it with yml like you did for the feature request ... so we should get 2 different templates one for bug reporting and another feature request ... hope you can do it I am adding gssoc tag to your issue

**Comment by andoriyaprashant** [comment]
sure @Arnabdaz

**Comment by andoriyaprashant** [comment]
Hello @Arnabdaz 
Please review my Pull request #148 
Thank you
