### ISSUE TITLE
website is not working

### ISSUE THREAD

**Issue by sumitkr2000** [agamjotsingh18/pollitup#145]
# Issue Template

## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Firmware Version:
* Operating System:
* SDK version:
* Toolchain version:

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Arnabdaz** [comment]
what part is not working can you describe?

**Comment by sumitkr2000** [comment]
Yesterday it was not working now it's fine

**Comment by sumitkr2000** [comment]
@Arnabdaz It's not working on the desktop but opening on mobile only. Let me share the screenshot.

![Screenshot (831)](https://github.com/agamjotsingh18/pollitup/assets/100675296/964f27d2-8538-4f77-a3bc-03999dbb2b66)

**Comment by sumitkr2000** [comment]
Can you let me know if it is opening on your PC or not?

**Comment by agamjotsingh18** [comment]
Might be due to catche, you can delete the cookies, if will work..

**Comment by Arnabdaz** [comment]
> @Arnabdaz It's not working on the desktop but opening on mobile only. Let me share the screenshot.
> 
> ![Screenshot (831)](https://user-images.githubusercontent.com/100675296/242805620-964f27d2-8538-4f77-a3bc-03999dbb2b66.png)

yep it is due to cache ... i also faced the issue but was fixed once deleted site data ... if you can fix this feel free to open a issue
