### ISSUE TITLE
[FEATURE] Want to add functionality to share the poll via link.

### ISSUE THREAD

**Issue by kartikjoshi267** [agamjotsingh18/pollitup#161]
### Description

Till now, there's no way to share the poll using a link. It would be convenient for the user to share the poll via a link so that the poll grasps maximum attention. So, I wanted to add a feature to generate a link for sharing the poll.

Can you please assign this issue to me as a part of GSSOC'23?

**Comment by Arnabdaz** [comment]
@kartikjoshi267 go ahead
