### ISSUE TITLE
Fix profile edit section create a new page for editing profile and the current profile page should be for sharing profile

### ISSUE THREAD

**Issue by Arnabdaz** [agamjotsingh18/pollitup#163]
### Current issue:

1. the profile page serves as both edit and profile display page users 
2. the edit profile does not work 
3. profile picture does not upload 
4. polls are not visible in the profile page

### expected behaviour:

1. profile page and profile edit page should be separate 
2. profile edit (such as name change / description changing ) should work
3. User created polls should show up in their profile
4. uploading /updating profile picture should work 

#### Note: on updating profile picture the old profile picture should be deleted from the database
<br>

### `$ Open to all gssoc 23 contributors`

**Comment by MahendraDani** [comment]
@Arnabdaz I would like to work on this issue!

**Comment by Arnabdaz** [comment]
@MahendraDani sure go ahead

**Comment by Arnabdaz** [comment]
@MahendraDani are you working on this issue ? if not someone else will be assigned

**Comment by debsouryadatta** [comment]
Yes, it needs to be fixed so that I can work on issue #187 ✌️

**Comment by MahendraDani** [comment]
Please assign someone else.

**Comment by debsouryadatta** [comment]
> Please assign someone else.

Okay then, let me work on it, can you please unassign yourself 👍
