### ISSUE TITLE
[FEATURE] Adding a search feature in Discover Page

### ISSUE THREAD

**Issue by komalioruganti** [agamjotsingh18/pollitup#165]
### Description

In the Discover page if there is a search feature it would be easy to sort the polls and get the data(result) from the required poll instead of searching through the page.

**Comment by komalioruganti** [comment]
Can you assign me this issue?

**Comment by komalioruganti** [comment]
I will implement it

**Comment by komalioruganti** [comment]
What can a user search for in the search bar? Poll name or Question name or description or all of them?

**Comment by Arnabdaz** [comment]
> What can a user search for in the search bar? Poll name or Question name or description or all of them?

i mean like if user can search all is good but it would be confusing for user .... rather we can set search filter like search by poll name or search by question or search by description ... like a drop down menu with these three options along side the search bar and accordingly search can be done ... if you think it is possible to be done i can increase the level to 3

**Comment by komalioruganti** [comment]
I think it's possible to do it. Let me try. I will update you on the progress.

**Comment by Arnabdaz** [comment]
okay, cool just add simple search with title and question if it is too hard for you.

**Comment by komalioruganti** [comment]
I am sorry for the late reply. I will get it done in a day and update you

**Comment by komalioruganti** [comment]
Hello! I made a pull request after adding the feature. Can you review it and also change the level from level 2 to level 3 because I executed search through poll name, question, and description? I included a video showing how everything is working. Do let me know if you want me to change anything.

**Comment by Arnabdaz** [comment]
Done
