### ISSUE TITLE
[FEATURE] Hovering Effect

### ISSUE THREAD

**Issue by parthpathakpp1** [agamjotsingh18/pollitup#178]
### Description

There should be a hovering effect on the images of the cards. Which will look good while hovering.

### Screenshots

**In this section -:**

https://github.com/agamjotsingh18/pollitup/assets/85991449/12918877-1ac9-4147-8ad6-075e70577ceb

**Comment by Arnabdaz** [comment]
it is not required at this moment because our main focus is to fix and improve the main functionalities at this moment
yah ofc if you can improve the ui/ux then this can be done

**Comment by parthpathakpp1** [comment]
> it is not required at this moment because our main focus is to fix and improve the main functionalities at this moment yah ofc if you can improve the ui/ux then this can be done

@Arnabdaz Okay no issues
