### ISSUE TITLE
[FEATURE] Create a contributors page

### ISSUE THREAD

**Issue by karthiknadar1204** [agamjotsingh18/pollitup#184]
### Description

Proposed solution:
Implement a contributors page which will be routed on the navbar, this page shall have the avatar of all the contributors in the form of cards along with links which shall redirect the user to their github accounts.

The avatar and the link will be beautifully aligned in different cards.The contributors will be placed in descending order of the pr's made to the project.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by Arnabdaz** [comment]
Already being implemented by #162 if you think you can help with fixing issues in that pr go ahead
