### ISSUE TITLE
[FEATURE] Add Captcha in Register Form

### ISSUE THREAD

**Issue by Manice18** [agamjotsingh18/pollitup#194]
### Description

I will like to add Captcha verification in the register form of the website.

### Screenshots

![image](https://github.com/agamjotsingh18/pollitup/assets/91601706/68a2d3cf-a4aa-466b-87cb-2601e359e4e3)
Somewhere below the confirm section i wanna add the captcha

**Comment by Arnabdaz** [comment]
@Manice18 go ahead

**Comment by Manice18** [comment]
@Arnabdaz i added the pr, can you plz check and tell
