### ISSUE TITLE
The visibility icon in sign up and sign in page is wrongly toggled

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [agamjotsingh18/pollitup#195]
### Description

The visibility icon when open the password should be visible and when closed password should be secured.
But in this project it is happening in contrast.
Please look at the screeshot and please assign this to me under gssoc23

### Screenshots

![image](https://github.com/agamjotsingh18/pollitup/assets/83866602/77152764-ca34-4493-a5e7-a4c006a4f150)

**Comment by Arnabdaz** [comment]
it is correct
