### ISSUE TITLE
Authentication with google

### ISSUE THREAD

**Issue by agamjotsingh18** [agamjotsingh18/pollitup#2]
Add authentication with google for register and login pages.

**Comment by FernandisNewton** [comment]
I want to work on this.
Can you assign me this issue?

**Comment by agamjotsingh18** [comment]
Sure @FernandisNewton

**Comment by ronitblenz** [comment]
I want to work on this issue, could you please assign me

**Comment by agamjotsingh18** [comment]
Sure @ronitblenz

**Comment by ronitblenz** [comment]
Plz  check and merge my PR

**Comment by ronitblenz** [comment]
Can you please check this PR?

**Comment by meghagangadhar13** [comment]
I want to work on this issue for gssoc, can you assign it to me. .
