### ISSUE TITLE
Footer designing

### ISSUE THREAD

**Issue by Soumyajit2825** [agamjotsingh18/pollitup#207]
### Description

The footer is looking odd
I mean it's not in the middle-bottom and also the "made by...." text is looking weird under the footer
I want to make them properly alligned.
Can I work on it??? @agamjotsingh18 

### Screenshots

![Screenshot 2023-06-22 180548](https://github.com/agamjotsingh18/pollitup/assets/100519291/3c8ab758-d1de-49e5-b63f-a9b25db61222)

**Comment by Arnabdaz** [comment]
@Soumyajit2825 go ahead also add the sitemap in the footer with the UI update

**Comment by Soumyajit2825** [comment]
![Screenshot 2023-06-28 220201](https://github.com/agamjotsingh18/pollitup/assets/100519291/5bd081f7-4ccc-41aa-bd5d-a4a2faf770fa)

Is it ok??
@Arnabdaz let me know your review

**Comment by Soumyajit2825** [comment]
@Arnabdaz @agamjotsingh18 Please have a look into it and let me know is it ok?
Or should I do more changes?

**Comment by Arnabdaz** [comment]
> @Arnabdaz @agamjotsingh18 Please have a look into it and let me know is it ok? Or should I do more changes?

can you put the copy right text below the follow on github button where there is some free space

**Comment by Soumyajit2825** [comment]
Ok sure

**Comment by Soumyajit2825** [comment]
![Screenshot 2023-06-29 114557](https://github.com/agamjotsingh18/pollitup/assets/100519291/88df57d2-a3e5-4a3a-ab40-bbfdd4504de1)
Check it once now @Arnabdaz

**Comment by Arnabdaz** [comment]
Remove the made with love part so only the footer you made is there

**Comment by Soumyajit2825** [comment]
@Arnabdaz so I will remove the whole made with love text right???

**Comment by Soumyajit2825** [comment]
> Remove the made with love part so only the footer you made is there

![Screenshot 2023-06-29 143840](https://github.com/agamjotsingh18/pollitup/assets/100519291/faca3ee7-e57e-44ad-9a03-5a83bf582917)

@Arnabdaz now check!!

**Comment by Arnabdaz** [comment]
LGTM :+1: make a pr

**Comment by Soumyajit2825** [comment]
Done @Arnabdaz 
Please Check!
