### ISSUE TITLE
Improve Poll Response UI

### ISSUE THREAD

**Issue by abhinavmalhotra01** [agamjotsingh18/pollitup#210]
### Description

The response output lacks clarity of the poll response in the case of textual polls
I will distribute the output in bar/pie charts for better understanding and clarity
Or distribute the output based on their occurrence in the polls.

### Screenshots

![image](https://github.com/agamjotsingh18/pollitup/assets/113239170/a4b5ab64-e304-4504-81da-0a4343c6fe26)

**Comment by Arnabdaz** [comment]
how can you catagorize text response with bar/pie chart ?

**Comment by abhinavmalhotra01** [comment]
I was thinking of number of occurrence to be shown next to it.

**Comment by Arnabdaz** [comment]
I don't think it makes sense ... this obviously needs improvement but not like text count as same word can be written like 
india, India, INDIA, InDiA, iNdIa etc ... and you might think of comparing them with lowercase but for some polls the uppercase and lowercases might have a significant meaning. 

Thanks for highlighting this problem I hope you can come up with some better solution

**Comment by abhinavmalhotra01** [comment]
can i work on improving the design of poll results for mcq category ? like similar to whatsapp poll's results in that
and the poll's result should indicate popularity of choices , so I thought occurrence might be helpful, Sorry for inconvenience.

**Comment by Arnabdaz** [comment]
> can i work on improving the design of poll results for mcq category ? like similar to whatsapp poll's results in that and the poll's result should indicate popularity of choices , so I thought occurrence might be helpful, Sorry for inconvenience.
there is nothing about inconvenience. I am happy that you are trying to contribute so keep the motivation up
you can create a new issue regarding the whatsapp like poll for multi option poll
