### ISSUE TITLE
Bug in DISCOVER page

### ISSUE THREAD

**Issue by marshadkhn** [agamjotsingh18/pollitup#217]
### Description

Hey @Arnabdaz and @agamjotsingh18 
**I checked all the assigned and unassigned issue and checked the website too while checking the website I found the DISCOVER  page some errors** 

### Problem 
A drop-down name as` By poll name` is not aligned 

### Screenshots

![Screenshot 2023-06-24 110312](https://github.com/agamjotsingh18/pollitup/assets/80325579/9379e776-256c-4dfc-b5d1-5f0dae1603c7)
### 
_Assign me this issue!_

**Comment by Arnabdaz** [comment]
@marshadkhn connect the dropdown and searbar together so they feel like they are in same div and make the search button of the size of the search box so ... the drop down , search bar text field and search button seem together...

**Comment by marshadkhn** [comment]
Ok @Arnabdaz I will do that
