### ISSUE TITLE
[FEATURE]  Valid Input Constraint in Create Poll

### ISSUE THREAD

**Issue by AlfiyaSiddique** [agamjotsingh18/pollitup#220]
## Description
Currently, in create poll section I can create a poll even with single characters which have no meaning and are invalid. It happens because there are no constraints in create poll fields. I can also implement real-time validation for these fields.

## Solution
We have to implement constraints for these fields, according to me following constraints can be applied
Poll Name: Min 4 characters
Description: Min 10 max 50 words
Question: Min 4 words
Multiple Choice: Min 3 characters

## Screenshots

<img width="414" alt="poll" src="https://github.com/agamjotsingh18/pollitup/assets/86224794/e6e72168-e2df-49e4-a81d-7ce5d13a7f98">

## Request
If you find this worth implementing then please assign me this under gssoc23 label.

**Comment by Arnabdaz** [comment]
@AlfiyaSiddique just add min limit no max limit and while doing the character counting don't forget to use trim() to remove trailing empty characters

**Comment by AlfiyaSiddique** [comment]
> @AlfiyaSiddique just add min limit no max limit and while doing the character counting don't forget to use trim() to remove trailing empty characters

Got it 👍
