### ISSUE TITLE
[FEATURE] Sitemap Addition for website {GSSoc'23}

### ISSUE THREAD

**Issue by NikhilRaikwar** [agamjotsingh18/pollitup#227]
### Description

Yes, the feature request is related to a problem. The problem is that the current website lacks a sitemap. Without a sitemap, it becomes challenging for search engines and users to navigate and discover all the pages and content on the site. This can result in lower search engine rankings, decreased visibility, and a poor user experience.

### Screenshots

![pollitup](https://github.com/agamjotsingh18/pollitup/assets/70462831/1557d8e1-7a3a-416d-9d45-6166f570412f)

In the attached screenshot, I have highlighted the website name with the expected presence of a sitemap.xml file. However, upon inspection, it is evident that the sitemap is not being displayed. This screenshot underscores the problem of the current website lacking a visible sitemap, further emphasizing the need for its implementation.

**Comment by Arnabdaz** [comment]
@NikhilRaikwar go ahead

**Comment by NikhilRaikwar** [comment]
@Arnabdaz Hey I'm done my work. Pls review the PR.
