### ISSUE TITLE
[FEATURE] Add hover effect to the navbar elements and add redirect link to logo too

### ISSUE THREAD

**Issue by PoulavBhowmick03** [agamjotsingh18/pollitup#230]
### Description

Currently the navbar elements do not have any hover effect and that looks a bit pale. Would like to add some subtle hover effect to that in all the pages
Also, would like to add homepage redirect link to the logo in all pages

### Screenshots

![image](https://github.com/agamjotsingh18/pollitup/assets/133862694/4d64d29d-8bfa-46da-b24c-369c86c3bf58)

**Comment by PoulavBhowmick03** [comment]
@Arnabdaz Please assign this to me

**Comment by Arnabdaz** [comment]
@PoulavBhowmick03 go ahead

**Comment by Dimple-Choudhary** [comment]
@Arnabdaz  is @PoulavBhowmick03  working on this issue?
