### ISSUE TITLE
[FEATURE]  Share your profile to other apps.

### ISSUE THREAD

**Issue by saikiranreddy201** [agamjotsingh18/pollitup#235]
### Description

- Now the share button in the profile only copies your profile's URL to a clipboard, and then you manually have to share it with other apps.
- What if we can share with other desired apps there itself using a pop-up card? It would be a wonderful user experience.
- This can be done using a package called react share and I have implemented it in another repository. 
- I would like to add it to this project.
- This would be a perfect addition to this project.

### Screenshots

<img width="523" alt="image" src="https://github.com/agamjotsingh18/pollitup/assets/98690105/7a0104f3-3639-4710-bc3c-a20f16a84ec4">

**Comment by Arnabdaz** [comment]
@saikiranreddy201 go ahead ... for now I assigned it a level2 but can be decided later if to be upgraded to level3

**Comment by saikiranreddy201** [comment]
@Arnabdaz, Okay as you wish!
