### ISSUE TITLE
[FEATURE] Breadcrumb feature could be added

### ISSUE THREAD

**Issue by siddarthdayala** [agamjotsingh18/pollitup#237]
### Description

![image](https://github.com/agamjotsingh18/pollitup/assets/97626996/c9365373-5530-4d61-b124-b46629bbf50a)

A Breadcrumb feature could be added as shown in the screenshot as it improves user navigation across the whole website.
It adds more professionalism and user can easily navigate through the pages.

Please assign me to this issue under GSSoC'23

**Comment by siddarthdayala** [comment]
hey @Arnabdaz could you please look over the feature and assign me so that I could PR at the earliest?

**Comment by Arnabdaz** [comment]
we do not have so many pages to breadcrumb and it would also affect the design

**Comment by siddarthdayala** [comment]
Sure! I will close this issue then.
