### ISSUE TITLE
Copyright year incorrect.

### ISSUE THREAD

**Issue by KendallDoesCoding** [agamjotsingh18/pollitup#24]
Copyright year = 2021, it should be 2022

**Comment by Shubham29012001** [comment]
I would like to work on this issue for GSSoC '22. We can use the new Date function and then get the full year from it. Thus, it will dynamically take the current year and we don't have to manually change it every time. If no one is working on this issue, then can I go ahead with it?

**Comment by KendallDoesCoding** [comment]
Ok!

**Comment by KendallDoesCoding** [comment]
> I would like to work on this issue for GSSoC '22. We can use the new Date function and then get the full year from it. Thus, it will dynamically take the current year and we don't have to manually change it every time. If no one is working on this issue, then can I go ahead with it?

Yup, please go ahead. I can't assign you tho.

**Comment by agamjotsingh18** [comment]
Sure @Shubham29012001

**Comment by Shubham29012001** [comment]
Hey @agamjotsingh18, can you please check the PR?

**Comment by KendallDoesCoding** [comment]
Please link the PR to this issue @Shubham29012001

**Comment by Shubham29012001** [comment]
PR No #26

**Comment by KendallDoesCoding** [comment]
> PR No #26

You need to go to the PR, and in the description put: Fixes #24... Then, the issue will get linked to the PR

**Comment by KendallDoesCoding** [comment]
Thanks for linking the issue @agamjotsingh18
