### ISSUE TITLE
Issue & PR templates

### ISSUE THREAD

**Issue by KendallDoesCoding** [agamjotsingh18/pollitup#25]
I can work on this, please assign me.

**Comment by agamjotsingh18** [comment]
Sure @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> Sure @KendallDoesCoding

Thanks.

**Comment by jyotivakare33** [comment]
@KendallDoesCoding are you still working on it?
@agamjotsingh18 Please assign the issue under GSSOC'22 to me.

**Comment by agamjotsingh18** [comment]
Sure @jyotivakare33

**Comment by agamjotsingh18** [comment]
Yup no problem..
You had 12 days and i still didn't removed the assignment from you.

**Comment by KendallDoesCoding** [comment]
> Yup no problem.. You had 12 days and i still didn't removed the assignment from you.

Thanks! You could've reminded by about it tho :)

**Comment by jyotivakare33** [comment]
@agamjotsingh18 Please review [pull-request](https://github.com/agamjotsingh18/pollitup/pull/40)

**Comment by KendallDoesCoding** [comment]
We can make a bug and feat issue template instead of just one.
