### ISSUE TITLE
footer redesign

### ISSUE THREAD

**Issue by Iamdivyak** [agamjotsingh18/pollitup#269]
### Description

there are 2 changes I want to make in the footer section.

1. adding a home page link in the logo.
2. "© 2023 PollItUp - All Rights Reserved" This line is in the bottom-most section of the footer.

please assign this issue to me

### Screenshots

<img width="948" alt="image" src="https://github.com/agamjotsingh18/pollitup/assets/102896170/9040e551-11c4-4717-aa96-6366e5fd4126">

**Comment by Iamdivyak** [comment]
kindly assign under gssoc

**Comment by agamjotsingh18** [comment]
Too easy issue!!
