### ISSUE TITLE
Error login in using Google/Gmail

### ISSUE THREAD

**Issue by KendallDoesCoding** [agamjotsingh18/pollitup#27]
This domain (pollitup.netlify.app) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.

**Comment by agamjotsingh18** [comment]
Sure you can @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> Sure you can @KendallDoesCoding

Idk how to do this, sorry. You need to do it as only you got access to Firebase, this is the error it gave me xD

**Comment by agamjotsingh18** [comment]
Done

**Comment by KendallDoesCoding** [comment]
lemme see if the error is fixed.
