### ISSUE TITLE
Add polls pointers to discover page

### ISSUE THREAD

**Issue by agamjotsingh18** [agamjotsingh18/pollitup#3]
Add pointers for the polls made by the user in the map of discover page

**Comment by Abhinav0909** [comment]
Hey @agamjotsingh18  this problem statement sounds interesting.Can I work on this issue?

**Comment by yogesh0509** [comment]
I would like to work on this issue under Hack Club RAIT but first, can you tell me more about this feature?

**Comment by agamjotsingh18** [comment]
Sure @yogesh0509

**Comment by agamjotsingh18** [comment]
Like in Maps we've pointer to describe a location, similarly in our discover page we need pointer to describe from where the poll has been submitted.

**Comment by yogesh0509** [comment]
Thanks, I will try it out!!

**Comment by arunavabasu-03** [comment]
I would like to work on this!

**Comment by vk20july** [comment]
@agamjotsingh18 sir I have quiet experience in this please can you assign me this issue under gssoc'23

**Comment by Arnabdaz** [comment]
fixed
