### ISSUE TITLE
Page not loading, works on Guest or incognito though.

### ISSUE THREAD

**Issue by KendallDoesCoding** [agamjotsingh18/pollitup#30]
2 console log errors which might be causing the issue, I reloaded the page and everything but still doesn't work on my main profile on Google.

![image](https://user-images.githubusercontent.com/84712013/156922798-304faac5-4e8c-4d3b-bb3e-232289b56ded.png)

Failed to load resource: the server responded with a status of 404 ()
main.de9036f1.chunk.js:1          Failed to load resource: the server responded with a status of 404 ()

**Comment by agamjotsingh18** [comment]
Yup, i changed to vercel.

**Comment by KendallDoesCoding** [comment]
> Yup, i changed to vercel.

Works now thanks.
