### ISSUE TITLE
Site not working when storing cookies

### ISSUE THREAD

**Issue by agamjotsingh18** [agamjotsingh18/pollitup#38]
Live preview doesn't works if cookies are stored (site works on incognito mode)

**Comment by Shubham29012001** [comment]
Can I work on this issue? Please assign it to me if possible.

**Comment by agamjotsingh18** [comment]
Sure @Shubham29012001

**Comment by Shubham29012001** [comment]
Hey @agamjotsingh18, can you please share more detail about the bug-like how I can produce it.

**Comment by agamjotsingh18** [comment]
Sure, 
When you open this live preview
https://pollitup-agamjotsingh18.vercel.app/
It doesn't open but if yo

**Comment by Shubham29012001** [comment]
Is the issue solved because you have closed it?

**Comment by agamjotsingh18** [comment]
No
