### ISSUE TITLE
profile page not showing the login user details

### ISSUE THREAD

**Issue by agamjotsingh18** [agamjotsingh18/pollitup#4]
login user details should be shown on the profile page

**Comment by Aniket-508** [comment]
@agamjotsingh18 I want to work on this issue under JWoC.

**Comment by agamjotsingh18** [comment]
Sure @Aniket-508

**Comment by 03amir** [comment]
I want to work on this issue under JWoC.

**Comment by jyotivakare33** [comment]
@agamjotsingh18 Please assign the issue to me under GSSOC'22 if it is still up for grabs

**Comment by agamjotsingh18** [comment]
Sure @jyotivakare33

**Comment by jyotivakare33** [comment]
Please review #57  @agamjotsingh18  and let me know if any changes required.

**Comment by jyotivakare33** [comment]
@agamjotsingh18 can we add merged lable here.
