### ISSUE TITLE
Add customised 404 page

### ISSUE THREAD

**Issue by rsinghcodes** [agamjotsingh18/pollitup#43]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

I want to add customised 404 page with well designed UI and with graphics or illustration and with some appropriate information like we should inform the user that he has jumped or redirected to wrong page or the page he is trying to find is not available.

## Current Behavior

404 page with white background and no appropriate information, what is the page showing?

### Steps to Reproduce

[View Issue here](https://pollitup-agamjotsingh18.vercel.app/404)

Please assign this issue to me under **GSSoC '22**.

Thanks!

**Comment by agamjotsingh18** [comment]
Sure @rsinghcodes

**Comment by rsinghcodes** [comment]
Hey @Paul0908, I'm working.
