### ISSUE TITLE
Bug in profile page

### ISSUE THREAD

**Issue by ajeetdangi2** [agamjotsingh18/pollitup#45]
# Issue Template

## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
On the profile page, the save button should be visible only when the user has clicked on the edit button

## Current Behavior

What is the current behavior?
The save button is visible all the time on the profile page

![Screenshot (98)](https://user-images.githubusercontent.com/72207545/164960212-0239ee43-43dc-4f4c-acea-b0f51f2c6c75.png)

@agamjotsingh18 Please assign this issue to me under GSSoC'22

**Comment by agamjotsingh18** [comment]
Sure @ajeetdangi2
