### ISSUE TITLE
Bug in create poll form

### ISSUE THREAD

**Issue by ajeetdangi2** [agamjotsingh18/pollitup#46]
# Issue Template

## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

A choice shouldn't be allowed to be empty in a poll with multiple choice.

## Current Behavior

What is the current behavior?
If a choice field is left empty in the create poll form then too it shows a success toast instead of an error.

![Screenshot (100)](https://user-images.githubusercontent.com/72207545/164960681-eb18f44f-9c76-491b-84c6-8d8d678995d9.png)

@agamjotsingh18 Please assign this issue to me under GSSoC'22

**Comment by agamjotsingh18** [comment]
Sure @ajeetdangi2

**Comment by yogesh0509** [comment]
Can I work on this issue under Hack Club RAIT ??

**Comment by yogesh0509** [comment]
I have fixed the issue but when trying `git push -u origin <branch-name>`, it shows me the error `remote: Permission to agamjotsingh18/pollitup.git denied to yogesh0509.`
