### ISSUE TITLE
poll submitted successfully should be shown after clicking submit button.

### ISSUE THREAD

**Issue by agamjotsingh18** [agamjotsingh18/pollitup#6]
after putting all details in creating poll page, submitted successfully should be shown when clicked on submit button

**Comment by yeshwanth235** [comment]
hey bro, I request you to assign this issue to me.

**Comment by psb27** [comment]
Please, assign this issue to me JWOC.

**Comment by agamjotsingh18** [comment]
Sure @yeshwanth235 ..
