### ISSUE TITLE
Change bot to display contributors (Issue #28)

### ISSUE THREAD

**Issue by KendallDoesCoding** [agamjotsingh18/pollitup#64]
Great! You managed to do it, but why did you delete the issue @agamjotsingh18 ?

**Comment by agamjotsingh18** [comment]
It was not needed now and also not the correct way to add contributors

**Comment by KendallDoesCoding** [comment]
How did you manage to resolve to merge conflicts tho?

> and also not the correct way to add contributors
wdym?
