### ISSUE TITLE
Add footer section

### ISSUE THREAD

**Issue by Akanksha-Sen** [agamjotsingh18/pollitup#67]
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

The website would contain a footer section mainly quoting name of the developer and also including some social platform links like github repo link for contribution. 

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**Comment by agamjotsingh18** [comment]
Sure, go ahead @Akanksha-Sen
