### ISSUE TITLE
Issue while storing Cookies

### ISSUE THREAD

**Issue by agamjotsingh18** [agamjotsingh18/pollitup#70]
# Issue Template

## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Firmware Version:
* Operating System:
* SDK version:
* Toolchain version:

## Expected Behavior

Please describe the behavior you are expecting
Cookies should be stored with the relevant information and site should be working.

## Current Behavior

What is the current behavior?
Site doesn't open when cookies are stores but it works if we delete the cookies stored.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Xaconi** [comment]
@agamjotsingh18 Hey there, can I get this issue?

**Comment by agamjotsingh18** [comment]
Sure @Xaconi

**Comment by Xaconi** [comment]
Need more info to solve this one...  There is a persistent bug on firebase connection, but after this I not see anything cookie-related. @agamjotsingh18 can you provide more info please?

**Comment by agamjotsingh18** [comment]
Yup working fine, might be firebase related issue
