### ISSUE TITLE
Add a section for HacktoberFest 

### ISSUE THREAD

**Issue by agamjotsingh18** [agamjotsingh18/pollitup#71]
# Issue Template

## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Firmware Version:
* Operating System:
* SDK version:
* Toolchain version:

## Expected Behavior

Please describe the behavior you are expecting
We can make a section for HacktoberFest with the beginner friendly projects to contribute to and resources for the guidance.

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by shashank-iter** [comment]
so basically you want a .md file in which contains information about hacktober fest 2022 ?? If so please assign this issue to me as I am interested to contribute.

**Comment by agamjotsingh18** [comment]
Nope, i wanted to have a page for HacktoberFest, this project is HacktoberFest accepted along with projects like these all beginner friendly projects you can contribute to...

**Comment by shashank-iter** [comment]
Sure I can contribute, what all content you need on that page, tell me in short I would be creating a page for you website or I can make the page in my way and you can review it later.

**Comment by agamjotsingh18** [comment]
You can add the top repos to contribute to HacktoberFest like cards in which a sneak peek of the website, repo name, description and link to repo. You can style it in your way.

Just add this repo at the beginning
https://github.com/agamjotsingh18/pollitup

**Comment by shashank-iter** [comment]
> You can add the top repos to contribute to HacktoberFest like cards in which a sneak peek of the website, repo name, description and link to repo. You can style it in your way.
> 
> Just add this repo at the beginning https://github.com/agamjotsingh18/pollitup

i checked the files and found that the  website is made using react and i am not a react developer i can make great pages with html css and js currently , i dont know whether i can contribute or not.

**Comment by lucidrohit** [comment]
I am a react developer, i recently made a portfolio(lucidrohit.vercel.app) for me. I can add a section for hacktoberfest. would you provide me design of that so that i can start or i have to make it my own?

**Comment by agamjotsingh18** [comment]
Sure @lucidrohit, you can design it your own way with the provided instructions in the upper chats.

**Comment by agamjotsingh18** [comment]
> I am a react developer, i recently made a portfolio(lucidrohit.vercel.app) for me. I can add a section for hacktoberfest. would you provide me design of that so that i can start or i have to make it my own?

No issues, you can contribute to other open source projects, learning should not stop.

**Comment by lucidrohit** [comment]
Actually sir this is my first time to contribute in open source. So, i am not able to understand what issue template actually wants. So can you please elloborate what do you want in this section. I really want to work.

**Comment by agamjotsingh18** [comment]
Issue template is just the describing what the issue is, what it wants
so in this issue, We can make a new component for HacktoberFest connected with the navbar (a new page with the beginner-friendly projects to contribute to and resources for the guidance).
