### ISSUE TITLE
Create a page corresponding to forget password link | GSSoC '23

### ISSUE THREAD

**Issue by AmoghCreator** [agamjotsingh18/pollitup#94]
## Context

The currently existing forget password link does not correspond to a page where user can visit to complete their request of changing password.

## Expected Behavior

According to me there must exist two pages :-
 1. To verify user is the owner of the account, ( we can either have an OTP type input field where user has to enter the OTP, or we can have a simple page that tells that a email regarding reset of the password has been sent to the user)
 2. Upon verification the user is able to go forward and change password ( either by opening the email link or by entering the OTP)

My solution for now will focus on front end part.

## Current Behavior

Currently no pages corresonding to password reset exist.

**Comment by AmoghCreator** [comment]
OK, I will follow the Email verification direction, Thank You.

**Comment by AmoghCreator** [comment]
@aceta-minophen Please Review , https://github.com/agamjotsingh18/pollitup/pull/98

**Comment by Arnabdaz** [comment]
@AmoghCreator could you work on #122 also ?

**Comment by AmoghCreator** [comment]
> @AmoghCreator could you work on #122 also ?

Yes, I'll be happy to .
