### ISSUE TITLE
[GSSOC'23] Update README with GSSoC Banner and Add "Back to Top" Link

### ISSUE THREAD

**Issue by mkswagger** [agamjotsingh18/pollitup#95]
## Expected Behavior

I expected the banner in the README to accurately represent the GSSoC 23 event, showcasing the GSSoC logo, tagline, or related artwork instead of the "Hacktoberfest" banner.

## Current Behavior
Currently, the README displays the "Hacktoberfest" banner instead of the expected GSSoC 23 banner. This creates a mismatch between the displayed content and the actual event the project is associated with.

### Description
This issue involves updating the README file of the project. The current banner in the README displays "Hacktoberfest," which needs to be replaced with a banner representing "GSSSoC." Additionally, a "Back to Top" link should be added at the end of the README for improved navigation.

### Steps to Implement
Replace the existing "Hacktoberfest" banner in the README with a "GSSSoC" banner that aligns with the project's branding.
Add a "Back to Top" link at the end of the README, enabling users to easily navigate back to the top of the document.

### Expected Outcome
After implementing these changes, the README will accurately reflect the project's association with GSSSoC. The "Back to Top" link will provide convenient navigation for users browsing the document.

**Comment by mkswagger** [comment]
Hi , I am a contributor in GSSOC'23, Please assign this issue to me

**Comment by aceta-minophen** [comment]
It has been assigned to you, you can start working on it!

> Hi @agamjotsingh18, I am a contributor in GSSOC'23, Please assign this issue to me

**Comment by mkswagger** [comment]
> It has been assigned to you, you can start working on it!
> 
> > Hi @agamjotsingh18, I am a contributor in GSSOC'23, Please assign this issue to me

Yes, will start working on it
