### ISSUE TITLE
Footer and font 

### ISSUE THREAD

**Issue by shruti8302** [agamjotsingh18/pollitup#96]
@agamjotsingh18 As a part of GSSOC'23, I would like to improve the footer and font of the home page. Kindly assign me this issue.

**Comment by shruti8302** [comment]
@aceta-minophen I would like to change the alignment of the GitHub icon and the copyright in the footer section of the homepage. Also, I want to change the font properties of the homepage to improve the readability and look of the website.

**Comment by aceta-minophen** [comment]
@shruti8302 you should choose a bigger issue to be considered for GSSOC as this is too easy. Maybe you can combine more issues with this

**Comment by shruti8302** [comment]
Sure I will do that.
